-- Update restaurant multipliers per country for budgeting and meal price estimation

update public.country_price_config set restaurant_multiplier = 3.2 where country = 'United States';
update public.country_price_config set restaurant_multiplier = 3.2 where country = 'United Kingdom';
update public.country_price_config set restaurant_multiplier = 3.1 where country = 'Canada';
update public.country_price_config set restaurant_multiplier = 3.3 where country = 'Australia';
update public.country_price_config set restaurant_multiplier = 3.0 where country = 'Germany';
update public.country_price_config set restaurant_multiplier = 3.1 where country = 'France';
update public.country_price_config set restaurant_multiplier = 2.9 where country = 'Italy';
update public.country_price_config set restaurant_multiplier = 2.8 where country = 'Spain';
update public.country_price_config set restaurant_multiplier = 3.1 where country = 'Netherlands';
update public.country_price_config set restaurant_multiplier = 3.1 where country = 'Belgium';
update public.country_price_config set restaurant_multiplier = 3.8 where country = 'Switzerland';
update public.country_price_config set restaurant_multiplier = 3.0 where country = 'Austria';
update public.country_price_config set restaurant_multiplier = 3.6 where country = 'Sweden';
update public.country_price_config set restaurant_multiplier = 3.7 where country = 'Norway';
update public.country_price_config set restaurant_multiplier = 3.7 where country = 'Denmark';
update public.country_price_config set restaurant_multiplier = 3.6 where country = 'Finland';
update public.country_price_config set restaurant_multiplier = 3.1 where country = 'Ireland';
update public.country_price_config set restaurant_multiplier = 2.7 where country = 'Portugal';
update public.country_price_config set restaurant_multiplier = 2.6 where country = 'Greece';
update public.country_price_config set restaurant_multiplier = 2.7 where country = 'Poland';
update public.country_price_config set restaurant_multiplier = 2.7 where country = 'Czech Republic';
update public.country_price_config set restaurant_multiplier = 2.7 where country = 'Hungary';
update public.country_price_config set restaurant_multiplier = 2.8 where country = 'Romania';
update public.country_price_config set restaurant_multiplier = 2.8 where country = 'Japan';
update public.country_price_config set restaurant_multiplier = 2.4 where country = 'China';
update public.country_price_config set restaurant_multiplier = 2.7 where country = 'South Korea';
update public.country_price_config set restaurant_multiplier = 2.3 where country = 'India';
update public.country_price_config set restaurant_multiplier = 3.0 where country = 'Singapore';
update public.country_price_config set restaurant_multiplier = 3.2 where country = 'Hong Kong';
update public.country_price_config set restaurant_multiplier = 2.5 where country = 'Taiwan';
update public.country_price_config set restaurant_multiplier = 2.2 where country = 'Thailand';
update public.country_price_config set restaurant_multiplier = 2.2 where country = 'Malaysia';
update public.country_price_config set restaurant_multiplier = 2.1 where country = 'Indonesia';
update public.country_price_config set restaurant_multiplier = 2.1 where country = 'Philippines';
update public.country_price_config set restaurant_multiplier = 2.0 where country = 'Vietnam';
update public.country_price_config set restaurant_multiplier = 2.6 where country = 'Brazil';
update public.country_price_config set restaurant_multiplier = 2.4 where country = 'Mexico';
update public.country_price_config set restaurant_multiplier = 2.4 where country = 'Argentina';
update public.country_price_config set restaurant_multiplier = 2.7 where country = 'Chile';
update public.country_price_config set restaurant_multiplier = 2.3 where country = 'Colombia';
update public.country_price_config set restaurant_multiplier = 2.3 where country = 'Peru';
update public.country_price_config set restaurant_multiplier = 2.5 where country = 'South Africa';
update public.country_price_config set restaurant_multiplier = 2.2 where country = 'Egypt';
update public.country_price_config set restaurant_multiplier = 2.1 where country = 'Nigeria';
update public.country_price_config set restaurant_multiplier = 2.1 where country = 'Kenya';
update public.country_price_config set restaurant_multiplier = 3.4 where country = 'Israel';
update public.country_price_config set restaurant_multiplier = 2.3 where country = 'Turkey';
update public.country_price_config set restaurant_multiplier = 3.2 where country = 'United Arab Emirates';
update public.country_price_config set restaurant_multiplier = 2.8 where country = 'Saudi Arabia';
update public.country_price_config set restaurant_multiplier = 2.6 where country = 'Russia';
update public.country_price_config set restaurant_multiplier = 2.5 where country = 'Ukraine';
update public.country_price_config set restaurant_multiplier = 3.2 where country = 'New Zealand';
